package org.ctridg.Models;
import org.w3c.dom.*;

public class Attribute extends Field{
    private String visibility; 
    private String isId;
    private String isAutogenerated;
    private String minVal;
    private String maxVal;

    public Attribute(Element element){
        super(element);
        this.visibility = element.getAttribute("Visibility");
        this.isId = element.getAttribute("IsID");
        this.isAutogenerated = element.getAttribute("Derived");
    }
    public String getVisibility(){
        return visibility;
    }
    public String getIsId(){
        return isId;
    }
    public String getIsAutogenerated(){
        return isAutogenerated;
    }
    @Override
    public String toString(){
        return String.format("%s %s : %s%s %s",visibility, name, type, typeModifier, isId);
    }
}
